In [3]:
import torch
import numpy as np
import torch.nn as nn

In [2]:
'''
    1. Basic autograd with variable
    y = w * x + b
    differentiate w.r.t parameters
'''
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(2., requires_grad=True)

y = w * x + b
y.backward()

print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [4]:
'''
    2. Basic autograd with fully connected layer
'''
# Create two dimensional tensor
x = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.4522, -0.1739, -0.1692],
        [ 0.3306, -0.1562, -0.5751]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.2279, -0.3755], requires_grad=True)


In [7]:
optimizer = torch.optim.SGD(linear.parameters(), lr = 0.01)

# forward pass
pred = linear(x)

# compute loss
criterion = nn.MSELoss()
loss = criterion(pred, y)

print('loss: ', loss.item())

# back propagate
loss.backward()

# print out the gradients
print('dL/dw: ', linear.weight.grad)
print('dL/db: ', linear.bias.grad)

# 1-step gradient descent
optimizer.step()

# print the loss after 1-step gradient descent
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss:  1.515024185180664
dL/dw:  tensor([[ 0.9705,  0.1195, -0.8792],
        [ 1.5142, -0.0796, -0.5738]])
dL/db:  tensor([-0.3236, -0.4115])
loss after 1 step optimization:  1.4692074060440063


In [9]:
'''
    3. Loading data from numpy
'''
x = np.array([[1,2], [3,4]])

# convert numpy array to torch tensor
y = torch.from_numpy(x)

# convert torch tensor to numpy array
z = y.numpy()

print(x)
print(y)
print(z)


[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
